---
- name: Include Nginx role
  include_role:
    name: nginx

- name: Clone Repo
  git:
    repo: "https://github.com/VKCOM/lighthouse"
    dest: "{{ root_dir }}"
    version: "master"
  tags:
    - lighthouse

- name: Copy *.conf file for nginx
  template:
    src: "{{ role_path }}/templates/default.conf.j2"
    dest: "/etc/nginx/conf.d/default.conf"
    mode: '0644'
  notify: Restart nginx service
  tags:
    - lighthouse