---
- name: Install dependencies
  become: yes
  ansible.builtin.apt:
    pkg:
      - git
      - nginx
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Clone Lighthouse repository
  ansible.builtin.git:
    repo: "https://github.com/VKCOM/lighthouse.git"
    dest: "/var/www/lighthouse"
    version: master

- name: Configure nginx
  ansible.builtin.template:
    src: lighthouse.conf.j2
    dest: "/etc/nginx/conf.d/lighthouse.conf"
  notify: restart nginx